### ISSUE TITLE
Push struct in interrupt handler and pop in main loop

### ISSUE THREAD

**Issue by ValeriiKim** [SMFSW/cQueue#2]
Hello sir, at first thank you for your library!
I know that you recommended to use pop/push functions carefully when put them in interrupt handlers. But in my application (controller STM32F103C8T6) I want to push CAN frames in RX queue in interrupt (when receiving new frame) and pop in main `while` loop. The application protocol (UAVCAN) is responsible for assembly of CAN frames in appropriate transfer.
I declare next FIFO queue (as global variable):
```cpp
Queue_t canrx_queue;
```
The problem is that sometimes I get **wrong** (corrupt) data after doing `q_pop` (this happens in approximately 50-60% of cases). This function is placed in main loop:
```cpp
void receive_transfers(CanardInstance *const canard)
{
	CanardFrame rxf;
	CanardTransfer transfer;
	if (q_isEmpty(&canrx_queue))
	{
		return;
	}

	q_pop(&canrx_queue, &rxf); // <---- this rxf frame has corrupt payload sometimes

	const int8_t result = canardRxAccept2(canard, &rxf, 0, &transfer, NULL);
	if (result < 0)
	{
		usart2::usart_send_string("HERE!!!\n");
		// An error has occurred: either an argument is invalid or we've ran out of memory.
		return;
	}
	else if (result == 1)
	{
		// usart2::usart_send_string("HERE!\n");
		process_received_transfer(&transfer);
		canard->memory_free(canard, (void *)transfer.payload);
	}
	else
	{
		uint8_t *check = (uint8_t *)rxf.payload;
		uint8_t check_var = *check;
		usart2::usart_send_int(check_var, true);
		// GREEN_LED_ON;
		// GREEN_LED_OFF;
	}
}
```
This is how I put frames in FIFO in the interrupt:
```cpp
extern "C"
{
	void USB_LP_CAN1_RX0_IRQHandler(void)
	{
		if ((CAN1->RF0R & CAN_RF0R_FMP0) || (CAN1->RF1R & CAN_RF1R_FMP1)) 
		{
			uint32_t extended_can_id;
			size_t payload_size;
			uint8_t payload[8] = {0};
			bxCANPop(0, &extended_can_id, &payload_size, payload);
			CanardFrame rxf = {timer2::get_micros(), extended_can_id, payload_size, payload};
			q_push(&canrx_queue, &rxf);
		}
	}
}
```
Note that I have tried to invoke `q_pop` function right after `q_push` in the above interrupt handler: everything was fine (payload was correct). Also note that this interrupt is invoked with 1 second period.
The `CanardFrame` is defined as follows:
```cpp
typedef struct
{
    /// For RX frames: reception timestamp.
    /// For TX frames: transmission deadline.
    /// The time system may be arbitrary as long as the clock is monotonic (steady).
    CanardMicrosecond timestamp_usec;

    /// 29-bit extended ID. The bits above 29-th shall be zero.
    uint32_t extended_can_id;

    /// The useful data in the frame. The length value is not to be confused with DLC!
    /// If the payload is empty (payload_size = 0), the payload pointer may be NULL.
    /// For RX frames: the library does not expect the lifetime of the pointee to extend beyond the point of return
    /// from the API function. That is, the pointee can be invalidated immediately after the frame has been processed.
    /// For TX frames: the frame and the payload are allocated within the same dynamic memory fragment, so their
    /// lifetimes are identical; when the frame is freed, the payload is invalidated.
    /// A more detailed overview of the dataflow and related resource management issues is provided in the API docs.
    size_t      payload_size;
    const void* payload;
} CanardFrame;
```
What am I doing wrong?

**Comment by SMFSW** [comment]
Hello,

glad that you like the library.

I did that comment because depending one's implementation (like yours here, and mine a lot too), particular care should be taken when queue is filled (with `q_push` in any interrupt).

You need to disable interrupts when pulling from the queue.
Looks like you're working with STM32 HAL, then you shall use `diInterrupts` & `enInterrupts` calls (located in `arm_cmsis.h` header).
If you're working with Arduino, use `noInterrupts` & `interrupts`,
If you're using any other compilation toolchain, you may have to search for those asm macros.

Here is an example: in your code:
```
	}

	**diInterrupts();**
	q_pop(&canrx_queue, &rxf); // <---- this rxf frame **should not have anymore** corrupt payload
	**enInterrupts();**

	const int8_t result = canardRxAccept2(canard, &rxf, 0, &transfer, NULL);
```

This way, you will prevent any interrupt (Rx interrupt which is the one causing issue in your case) to trigger while you're pulling something from the queue.
No di/en of interrupts may lead to hazardous behaviors because of library internal handling (incrementing/decrementing index and counter) that happens while pushing/pulling items to the queue (semi operation done of pulling (unfinished), but reception interrupt is triggered and halts normal execution to push a new item to the queue; unfortunately the library is in an unfinished other business state).

Please keep in mind this di/en interrupts mechanism when you're working with code in interrupts, you may need it in many other cases (eg. getting a 64bit in interruption on a 32b platform, using the value in main loop.. often leads to get half the 64b ok, while the other 32b are from the newly read value).

I let you close the issue when you have tried it for yourself.

Regards,
SMFSW

**Comment by ValeriiKim** [comment]
Hello, thank you for your fast and detailed answer!
I suspected that I needed to disable the interrupts but hoped that I can avoid this routine. Now I understand why I was getting strange value of index in the queue while debugging my Bluepill.
I will correct my code and post here results.

**Comment by ValeriiKim** [comment]
Hello, eventually I found the source of my problem. At first I did as you recommended: disabled interrupts while pulling frame from the queue. But It didn't help (tried both global interrupts disable and disable of CAN receive interrupts). Turned up it was the issue with accessing a memory which was allocated for a local variable in the CAN interrupt handler.
```cpp
extern "C"
{
	void USB_LP_CAN1_RX0_IRQHandler(void)
	{
		if ((CAN1->RF0R & CAN_RF0R_FMP0) || (CAN1->RF1R & CAN_RF1R_FMP1)) 
		{
			uint32_t extended_can_id;
			size_t payload_size;
			uint8_t payload[8] = {0};          // <---- this payload will be destroyed at the end of IRQHandler
			bxCANPop(0, &extended_can_id, &payload_size, payload);
			CanardFrame rxf = {timer2::get_micros(), extended_can_id, payload_size, payload};
			q_push(&canrx_queue, &rxf); // <--- rxf payload is a pointer to a local payload
		}
	}
}
``` 
In this piece of code `payload` field of `rxf` (struct `CanardFrame`) is a `const void*` pointer which points to the local variable `payload`. This local `payload` stores the actual CAN data after `bxCANPop` but it will be destroyed at the end of `IRQHandler`. 
Inside `q_push` you use `memcpy` which in this case makes copy of struct that contains pointer to local `payload`. So when I pull data frame outside interrupt handler I get garbage (pointer points to some random area of memory).
So to solve this problem I have created another struct which contains array of actual `uint8_t` data (not pointer). So now interrupt handler looks like this:
```cpp
extern "C"
{
	void USB_LP_CAN1_RX0_IRQHandler(void)
	{
		if ((CAN1->RF0R & CAN_RF0R_FMP0) || (CAN1->RF1R & CAN_RF1R_FMP1)) // FMP0 > 0?
		{
			CAN_message can_msg;
			bxCANPop(0, &can_msg.extended_can_id, &can_msg.payload_size, can_msg.payload);
			can_msg.microseconds = timer2::get_micros();
			q_push(&canrx_queue, &can_msg);
		}
	}
}
```
And `CAN_message` is:
```cpp
struct CAN_message
{
	uint64_t microseconds;
	uint32_t extended_can_id;
	size_t payload_size = CANARD_MTU_CAN_CLASSIC;
	uint8_t payload[CANARD_MTU_CAN_CLASSIC] = {0};

	CAN_message()
	{
		microseconds = 0;
		extended_can_id = 0;
		payload_size = CANARD_MTU_CAN_CLASSIC;
	}
};
```
Maybe this is a crude solution but it seems that it works.
Thank you for your help anyway!

**Comment by SMFSW** [comment]
Great to hear that you found your (other) issue!
Please keep in mind you still need to disable/enable interrupts when pulling from queue (due to push done in interrupts), otherwise you can still get wrong results sometimes.

Yes, queue library uses memcpy without any limitation, this you can handle anything (from simple type to structure or pointers)... When dealing with pointers, you have to be careful the referenced content would be still available when pulling.

In your case, copying the contents is the best solution I think; this is the way I also handle it myself for CAN messages queues.

Regards, and thanks for your interest!
SMFSW
