### ISSUE TITLE
q_init() variant for statically allocated memory

### ISSUE THREAD

**Issue by matthias-bs** [SMFSW/cQueue#3]
Hi,

I'd like to have a variant of q_init() which uses a statically allocated chunk of memory.
Basically, it should be sufficient to replace
```
q->queue = (uint8_t *) malloc(size);
```
by
```
q->queue = (uint8_t *) buf;
```
where uint8_t * buf is passed as a parameter.

The reason  for my request is, that I would like to store the buffer and the queue_t structure in the ESP32's non-volatile RAM (RTC RAM), e.g.

```
RTC_DATA_ATTR Queue_t weather_logger;

typedef struct strRec {
	float temperature;
	float humidity;
        float pressure;
} Rec;

// FIFO for 24 hours; updated every hour
RTC_DATA_ATTR Rec weather_logger_data[24] ;
```
What do you think?

Best regards
Matthias

**Comment by SMFSW** [comment]
Hello,

thanks a lot for your interest in `cqueue` library.

In fact, I already thought about being able to statically define the queue data address for software certification aspects where dynamically allocated memory is either not welcomed or completely forbidden.
Your reason is a very good one too, I did not think about it, never had yet encountered such a case.

I will have to think a little more about its implementation, but my first thoughts are:
- adding another init function like `q_init_static()` so that the library remains totally compatible with any code already using it
- `q_init_static` would still needs size and number of items
I'm just thinking about a way to ensure statically allocated memory size is enough, not to cause any overflow, which would mean a length parameter would have to be passed to `q_init_static` basically filled by a `sizeof(StaticMemoryArea)`.

Let me know if you have any other idea on this matter.

I will make the changes and size optimizations (most likely both init functions would call the same internal and static init function) probably during next week.

In the meantime, don't hesitate to share your thoughts on this new functionality.

Thanks a lot,
Kind regards,
SMFSW

**Comment by matthias-bs** [comment]
Hello,

thanks a lot for your quick and kind response. I think I got it working already. Maybe I'm able to provide a proposal as PR soon.
Indeed I think my implementation seems to be quite close to what you described.

Best regards
Matthias

**Comment by matthias-bs** [comment]
Perfect! Thank you very much for the quick implementation!
